# Generated by Django 2.0 on 2018-12-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181207_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='oeuvre',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='musee_api/photos/'),
        ),
    ]
