# Generated by Django 2.0 on 2018-12-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181208_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oeuvre',
            name='image_path',
        ),
    ]
